### ISSUE TITLE
Handle data migration better

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#200]
## Background

Sometimes adding features requires us to migrate existing data that has been saved into the users local storage.

I've attempted several times to apply a nice pattern for migrations, and although each new attempt is cleaner than the previous I'm still not happy with the current state. At a high level this has resulted in some of the following problems/code smells:

* Migrations are tied to version release numbers
    * Makes the scripts large and complex
    * Makes it hard to release multiple migrations in a single versioned release
       * Unless you update the migration script, which won't work if its already been applied
   * If a versioned release doesn't have any features that require a migration the 'local storage version' won't actually match the app version
    * Unless you add a migration just to update the version number stored

I think a better approach would be to use something similar to [Flyway](https://flywaydb.org/) and other relational database migration tools. This would allow us to have smaller more understandable migration scripts and explicitly check which migrations have been applied.

Any thoughts or advice welcome!

## Additional

1. Since we are close to releasing v1.0.0 is it reasonable to just migrate going forward and not allow any pre v1.0.0 to be imported?

I've decided we should only support migrating data from v1.0.0+
  
## Migrations required

- [x] `audioVisual` key to `settings`
- [x] ~trayIds to UUIDs~ (I've decided this is too much effort)
- [x] #253 flatten projects
- [x] `password` key to `encryptedPassword`
- [x] `accessToken` key to `encryptedAccessToken`
- [x] add the `authType` to trays (this was previously done in the selector but got removed in a recent refactor)

## Tasks

- [x] Add configuration exports for major releases to `docs` folder
    - [x] v1.0.0
    - [x] v2.0.0
    - [x] v3.0.0
    - [x] v4.0.0
- [x] ~Add a functional tests~
  - [x] ~Imports from v1.0.0 export~
  - [x] ~Imports from v2.0.0 export~
  - [x] ~Imports from v3.0.0 export~
  - [x] ~Imports from v4.0.0 export~

I've decided trying to write functional tests to import from previous versions is probably more effort than its worth.

**Comment by GentlemanHal** [comment]
@cowley05 @joejag and I discussed this. We will try out using a FlyWay style migration which allows us to use fine grained migrations like: `20190817_move_audiovisual_to_settings.ts`.

These migrations will be recorded as played in a migration reducer and stored in LocalStorage. We will have to be careful for existing states and skip when not required.

This code will run on pressing the "import" button and also when initializing the page from LocalStorage. We think it would be good to show a visual indicator on the import page when the migrations are being applied.

We are also considering whether it is worth changing the startup sequence so the migration code runs before the Redux store is created.
